# Generated by Django 5.0.6 on 2024-06-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Не обязательно', null=True, verbose_name='Описание товара'),
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество проданного товара')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая сумма продажи')),
                ('sale_date', models.DateField(verbose_name='Дата продажи товара (в количестве 1-ой штуки)')),
                ('description', models.TextField(blank=True, help_text='Не обязательно', null=True, verbose_name='Описание товара')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания объекта')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Выполнен'), (2, 'Отказано'), (3, 'В рассрочку')], default=1, verbose_name='Статус продажи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Товар')),
            ],
        ),
    ]
