# Generated by Django 5.0.6 on 2024-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description_soldproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='core/static/images/Premium Photo _ Concrete pedestal for product display with grey background 3d rendering.jpeg', null=True, upload_to='media/product_cover', verbose_name='Фото товара'),
        ),
    ]
