# Generated by Django 5.0.6 on 2024-06-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldproduct',
            options={'verbose_name': 'Проданный товар', 'verbose_name_plural': 'Проданные товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateTimeField(verbose_name='Дата завоза товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/product_cover/default_photo.jpeg', null=True, upload_to='media/product_cover', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='sale_date',
            field=models.DateField(verbose_name='Дата продажи товара'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма продажи'),
        ),
    ]
