# Generated by Django 5.0.6 on 2024-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_soldproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateField(verbose_name='Дата завоза товара'),
        ),
    ]
