# Generated by Django 5.0.6 on 2024-06-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=223, verbose_name='Цвет товара'),
        ),
    ]
